
# name: Deploy Infrastructure with Terraform

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   terraform:
#     name: 'Terraform Deployment'
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.9.3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.MAIN_AWS_ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.MAIN_AWS_SECRET_KEY }}
#           aws-region: us-east-1

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Code Linting Check
#         if: github.event_name == 'pull_request'
#         run: terraform fmt -check -recursive

#       - name: Checkov Terraform Code Security Check
#         if: github.event_name == 'pull_request'
#         run: docker run --tty --volume ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --soft-fail

#       - name: Terraform Plan
#         id: plan
#         if: github.event_name == 'pull_request'
#         run: terraform plan

#       - name: Terraform Apply
#         if: github.event_name == 'push'
#         run: terraform apply -auto-approve
